fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    apt:
      repo: "git://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "2.2.2"
    logrotate:
      repo: "git://github.com/voxpupuli/puppet-logrotate.git"
      ref: "v1.4.0"
  symlinks:
    mongodb: "#{source_dir}"
